function Hd = EllipticFilter
%ELLIPTICFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the DSP System Toolbox 8.5.
% Generated on: 05-Mar-2017 13:12:40

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N      = 10;   % Order
Fpass1 = 0.5;  % First Passband Frequency
Fpass2 = 50;   % Second Passband Frequency
Apass  = 1;    % Passband Ripple (dB)
Astop  = 50;   % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ast1,Ap,Ast2', N, Fpass1, Fpass2, ...
                      Astop, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]

%如何调用该函数：Hd=EllipticFilter; yyy=filter(Hd,val);
